apiVersion: v1
kind: Service
metadata:
  name: web-carshop
  namespace: carshop
spec:
  selector:
    app: web-carshop
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-carshop
  namespace: carshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-carshop
  template:
    metadata:
      labels:
        app: web-carshop
    spec:
      containers:
        - name: web-carshop
          image: ghcr.io/ttala/carshop:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL

